# docker build -f Dockerfile.tests .
FROM python:3.9-slim-bullseye

WORKDIR /bx_django_utils
RUN set -x \
    && apt-get update \
    && apt-get install -y git-core make curl \
    && rm -rf /var/lib/apt/*

ENV PATH="/root/.local/bin:${PATH}"

# Install Poetry + requirements + Playwright
COPY Makefile pyproject.toml poetry.lock ./
RUN set -x \
    && make install-poetry \
    && make install || true \
    && make playwright-install \
    && poetry run playwright install-deps

COPY . .

# List installed packages
RUN set -x \
    && poetry run pip freeze \
    && poetry show --tree

# Run unittests
RUN make test

# Run unittests via tox
RUN make tox

# Run linters
RUN make lint

