# Generated by Django 3.1.4 on 2020-12-18 09:19

import bx_py_utils.data_types.gtin.model_fields
import bx_py_utils.data_types.gtin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOrUpdateTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(blank=True, editable=False, help_text='ModelTimetrackingMixin.create_dt.help_text', null=True, verbose_name='ModelTimetrackingMixin.create_dt.verbose_name')),
                ('update_dt', models.DateTimeField(blank=True, editable=False, help_text='ModelTimetrackingMixin.update_dt.help_text', null=True, verbose_name='ModelTimetrackingMixin.update_dt.verbose_name')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GtinFieldTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gtin', bx_py_utils.data_types.gtin.model_fields.GtinModelField(max_length=14, validators=[bx_py_utils.data_types.gtin.validators.GtinValidator(accepted_length=(12, 13, 14))], verbose_name='GTIN')),
                ('all_gtin', bx_py_utils.data_types.gtin.model_fields.GtinModelField(max_length=14, validators=[bx_py_utils.data_types.gtin.validators.GtinValidator(accepted_length=(12, 13, 14))], verbose_name='GTIN')),
                ('ean13', bx_py_utils.data_types.gtin.model_fields.GtinModelField(max_length=14, validators=[bx_py_utils.data_types.gtin.validators.GtinValidator(accepted_length=(12, 13, 14))], verbose_name='GTIN')),
            ],
        ),
        migrations.CreateModel(
            name='TimetrackingTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(blank=True, editable=False, help_text='ModelTimetrackingMixin.create_dt.help_text', null=True, verbose_name='ModelTimetrackingMixin.create_dt.verbose_name')),
                ('update_dt', models.DateTimeField(blank=True, editable=False, help_text='ModelTimetrackingMixin.update_dt.help_text', null=True, verbose_name='ModelTimetrackingMixin.update_dt.verbose_name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
