# Generated by Django 3.2.15 on 2022-09-21 15:09

import uuid

from django.db import migrations, models

import bx_django_utils.credentials.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                (
                    'create_dt',
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text='ModelTimetrackingMixin.create_dt.help_text',
                        null=True,
                        verbose_name='ModelTimetrackingMixin.create_dt.verbose_name',
                    ),
                ),
                (
                    'update_dt',
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text='ModelTimetrackingMixin.update_dt.help_text',
                        null=True,
                        verbose_name='ModelTimetrackingMixin.update_dt.verbose_name',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Credential.id.help_text',
                        primary_key=True,
                        serialize=False,
                        verbose_name='Credential.id.verbose_name',
                    ),
                ),
                (
                    'key',
                    models.CharField(
                        help_text='Credential.key.help_text',
                        max_length=255,
                        unique=True,
                        verbose_name='Credential.key.verbose_name',
                    ),
                ),
                (
                    'secret',
                    bx_django_utils.credentials.fields.EncryptedCharField(
                        help_text='Credential.secret.help_text',
                        max_length=255,
                        verbose_name='Credential.secret.verbose_name',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
